### ISSUE TITLE
GetAllCookies fails due to duplicate key

### ISSUE THREAD

**Issue by dornech** [GCuser99/SeleniumVBA#122] opened 2024-10-16 15:34 UTC
I have an error in GetAllCookies because an website provides two cookies with same name but different domains.
Strange thing is: the domain is once a proper domain www.ariva.de, the other time a not proper domain like .www.ariva.de.

I know this is not primarly a SeleniumVBA issue but it might be helpful to prevent this in a controlled manner via a parameter  (not saying not to throw a warning)?
And/or to allow to filter "improper" domains ?

**Comment by dornech** [comment] 2024-10-16 16:17
I did some investigation. It seems like duplicate cookies is a problem that occurs with some websites. so, it seems to me beneficial to prevent SeleniumVBA from throwing an error in case such a situation occurs. in the addin I just ignored the error (i e the duplicate cookie) and it works for my purpose. But for using the DLL and others a more general solution might look dersirable.

**Comment by GCuser99** [comment] 2024-10-16 16:34
Thanks for reporting @dornech. Can you provide an image showing the error that is thrown? Or better, some reproducible code with use-case. Otherwise, I will have to spend a lot of time trying to define the problem, in addition to implementing a solution.

Thanks again for your help!

**Comment by dornech** [comment] 2024-10-16 17:40
Here you go: 
![image](https://github.com/user-attachments/assets/d5f85d2f-fff5-4355-bacd-a3a1514366b8)
Sorry for the German - but it says "Key already in Collection" / duplicate key.

The error occurs in GetAllcookies in at line 1936.
cookies.Add cookie

Just to explain the use case - it is not really an issue of client-side code: I do some automated download from a website which requires a login for allowing the download. Authorization data is created when logging in and is obviously stored in cookies. So i use Selenium to do the login, then trying to extract the cookies and to create a WinHHTP request to retrieve the desired data (worked with SeleniumBasic). The problem occurs when I retrieve the cookies to create a cookie header for the subsequent HTTP request.

I analyzed the repsonse from the execute(tCMD.CMD_GET_ALL_COOKIES)("value") call and the erroneous entry and I found the second cto_bundel as cause for the error.
{"value":[
{"domain":"www.ariva.de" ...}, ... 
{"domain":".www.ariva.de","expiry":1762798032,"httpOnly":false,"name":"cto_bundle","path":"/","sameSite":"Lax","secure":false,"value":"..."}, 
...
{"domain":"www.ariva.de","expiry":1762794436,"httpOnly":false,"name":"cto_bundle","path":"/","sameSite":"Lax","secure":false,"value":"..."},
...]}

I just bracketed line 1936 with an On Error Resume Next / On Grror Goto 0 pair of statements and it worked again. so a solution coud look like
```
Public Function GetAllCookies(Optional bIngoreDuplicatesError as Boolean) As WebCookies
Attribute GetAllCookies.VB_Description = "Returns the collection of cookies for the current webpage"
    Dim resp As Collection
    Dim cookie As WebCookie
    Dim cookies As WebCookies
    Set resp = execute(tCMD.CMD_GET_ALL_COOKIES)("value")
    Set cookies = Me.CreateCookies
    Dim i As Long
    For i = 1 To resp.Count
        Set cookie = New WebCookie
        If resp(i).Exists("name") Then cookie.Name = resp(i)("name")
        If resp(i).Exists("domain") Then cookie.Domain = resp(i)("domain")
        If resp(i).Exists("expiry") Then cookie.ExpiryUnix = resp(i)("expiry")
        If resp(i).Exists("httpOnly") Then cookie.HttpOnly = resp(i)("httpOnly")
        If resp(i).Exists("sameSite") Then cookie.SameSite = resp(i)("sameSite")
        If resp(i).Exists("secure") Then cookie.Secure = resp(i)("secure")
        If resp(i).Exists("value") Then cookie.Value = resp(i)("value")
        If resp(i).Exists("path") Then cookie.Path = resp(i)("path")
        On Error Resume Next
        cookies.Add cookie
	If Err.number <> 0 Then
            debug.print "Duplicate cookie '" & cookie.Name & "' for domain '" & cookie.Domain & '."
        End If
        On Error Goto 0
    Next i
    Set GetAllCookies = cookies
End Function
```

**Comment by dornech** [comment] 2024-10-16 17:42
BTW: this is an example why I do like the possibility to switch between DLL and addin easily: in general I like to have just one DLL for Excel an Access but to be able to debug issues in the SeleniumVBA code

**Comment by GCuser99** [comment] 2024-10-16 19:58
Excellent issue report - thank you for taking the time to lay it out so clearly.

Obviously, the error you got was caused by my incorrect assumption that cookie names are unique and so then could be used as collection keys in order to retrieve any cookie from the collection by name (key).

A simple solution would be when adding a cookie to the cookies collection, the code could first check if a cookie with same name already exists, and if it does then use a unique collection key for the duplicate named cookie(s). In that way you would be able to iterate through the entire collection (including the duplicates) with `for each` or `i=1 to cookies.count.` You could also use `cookies.Item("[cookie name]")` to retrieve the cookie by name but obviously that would retrieve the first cookie with that name, which in your use-case above would happen to be the one with the invalid domain name.

Do you use `cookies.Item("[cookie name]")` in your use-case code?

With that solution, it would be up to the user to check for duplicate named cookies by iterating the collection and then take desired action to resolve, if needed.

We could add a boolean property to the Cookies object like `cookies.HasDuplicateName` that alerts user to the issue, if you think that would be of use.

I can think of more complicated solutions, such as `cookies.Item("[cookie name]")` returning either a single cookie object if uniquely named, or a collection of identically named cookie objects, whichever is applicable. The downside is that `Item` would have to be typed as `Object`, and so would lose IntelliSense. But given my current understanding that this is not a common issue, I'm wondering if the extra complication is justified? I don't mind implementing this solution if you really think the issue is common enough and you feel that would be of great use.

Another thing I always think about is whether considered changes will break our userbase's already existing code. At first thought, I don't believe either of the two solutions above would do that.

One thing I would like to avoid getting into is resolving the invalid domain - I think invalid cookie attributes should be handled on the user's end, not by the code.

What do you think, simple solution, less simple solution, or something else that won't break preexisting code?

**Comment by dornech** [comment] 2024-10-16 20:20
Hi Mike, thanks for your thoughts. I appreciate your efforts very much.

To start at the end: I absolutely agree - fixing potentially invalid or strange domains is not with SeleniumVBA. I just mentioned this for completness reasons - only idea was to consider, if an assignment to a incorrect domain would be a selection criteria to ignore duplicates (would work in my specific case) - but it is not a really general solution.

As mentioned above, my really quick solution was to ignore the second duplicate cookie - worked for me but probably is not the right solution for a general approach.
A more graceful solution is what you suggest but I would porbably extend it: use a name2 in the cookie object to preserve the original name and use a postfix for the name / key to avoid duplicate keys. Then duplicate key cookies can be found with name <> name2. And with looping and reading name2 the original collection is available. 
As you suggest, an additional flag in the cookies collection to mark if a duplicate was found would be helpful to flag that a cookie duplicates handling is neccessary when evaluating cookies.

I think a collection of duplicates looks a little bit overengineered.

**Comment by GCuser99** [comment] 2024-10-16 23:09
Thanks for your reply. I'm hesitant to add a new property to the WebCookie class that will hold the "postfix" name because in theory, "duplication" is relative to membership in a WebCookies object, and a WebCookie can, in theory, belong to more than one WebCookies objects, thus changing its duplication status.

So I tested the following changes to WebCookies class:

1. Ensuring unique collection keys when a WebCookie is added to a WebCookies object
2. Adding Function `HasDuplicateNames(Optional ByVal cookieName As String) As Boolean` for duplicate detection
3. Adding Function `FilterByName(ByVal pattern As String) As WebCookies` to return duplicates for a given name

With those changes, you would be able to do the following:

```vba
    Set cks = driver.CreateCookies
    
    'get cookie, change it's value, and then add it to WebCookies object
    Set ck = driver.GetCookie("Selenium"): ck.Value = 1
    cks.Add ck
    
    Set ck = driver.GetCookie("Selenium"): ck.Value = 2
    cks.Add ck
    
    Set ck = driver.GetCookie("Selenium"): ck.Value = 3
    cks.Add ck
    
    i = 0
    For Each ck In cks
        i = i + 1
        Debug.Assert ck.Value = i
    Next ck
    
    For i = 1 To cks.Count
        Debug.Assert cks(i).Value = i
    Next i
    
    Debug.Assert cks.HasDuplicateNames() = True
    Debug.Assert cks.HasDuplicateNames("Selenium") = True
    Debug.Assert cks.HasDuplicateNames("Uranium") = False
    
    Debug.Assert cks("Selenium").Value = 1 'finds first one
    
    'how to get the second duplicate using FilterByName which returns a WebCookies object
    If cks.HasDuplicateNames("Selenium") Then
        Debug.Assert cks.FilterByName("Selenium")(2).Value = 2
    End If
    
    'another way, to get the third one
    If cks.FilterByName("Selenium").Count > 1 Then
        Debug.Assert cks.FilterByName("Selenium")(3).Value = 3
    End If
    
    If cks.HasDuplicateNames() Then
        'we know there are dups, but don't know which
        For Each ck In cks
            If cks.FilterByName(ck.Name).Count > 1 Then
                Debug.Print "duplicate name found: " & ck.Name
            End If
        Next ck
    End If
```
Do you think you can live with that solution?

**Comment by dornech** [comment] 2024-10-16 23:34
I am afraid I do not fully understand what you mean. My problem is not creating an own Cookies class and members in there  -when I was talking about setting the HTTP header with the cookies this is a pure string I just loop through the Cookies collection derived via calling GetAllCookies to build this HTTP header string. So the issue lies within the GetAllCockies method and I am afraid I missed the point how your apporach fixes this.

**Comment by GCuser99** [comment] 2024-10-16 23:54
Sorry, the above code I shared was used to **test the proposed new functionality** of the WebCookies object, which GetAllCookies returns. If all you need to do is iterate the WebCookies object and build a string, irrespective of duplicate names, then you may not need the HasDuplicateNames and FilterByName methods. Maybe all I need to do is ensure that all of the cookies are there (prevent the duplicate error from being raised), whether dups or not?

**Comment by dornech** [comment] 2024-10-17 08:14
In principle yes, however identification of duplicates might be helpful (and probably necessary in other situations). As mentioned, as quick fix I just threw away the duplicates and it worked in my specific situation - if duplicates are in the string, it could cause problem but that I did not figure out. But primarily the issue arises not in my own code but in the GetAllCookies method. So it is necessary that GetallCookies does not abort when duplicates are in the cookies. As you mentioned, the implicit assumption of unique cookie names is nothing one can rely on (even it sounds logical) but seems only true in conjunction with the domain.

**Comment by GCuser99** [comment] 2024-10-17 12:38
To use your phrase, I think I was "over-engineering" a solution to my original bad engineering! The simple solution is not to use a keyed collection for cookies. So I refactored WebCookies as a very simple un-keyed collection wrapper. No dups handling functionality. Hopefully that gets you back up and running using the DLL. If in moving forward you find a compelling need for enhanced WebCookie(s) functionality, then we can discuss more. Thanks again for your issue reports!

**Closed as completed** 2024-10-17 12:42 UTC
